sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
dist:
  xenial
#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: true
install: pip install tox-travis coveralls pyserial-asyncio pytest-asyncio
script:
  - tox
  - coverage run --source pyduofern -m py.test
  - coverage report -m
after_success:
  - coveralls