sudo: false
language: python
python:
  - "3.5"
  - "3.6"
install: pip install tox-travis coveralls
script:
  - tox
  - coverage run --source pyduofern -m py.test
  - coverage report -m
after_success:
  - coveralls