sudo: false
language: python
python:
  - "3.8"
  - "3.9"

install: pip install tox-travis coveralls pyserial-asyncio pytest-asyncio
script:
  - tox
  - coverage run --source pyduofern -m py.test
  - coverage report -m
after_success:
  - coveralls